### ISSUE TITLE
scripts/vscode seems to not work or exit

### ISSUE THREAD

**Issue by idkjs** [kyldvs/template-reason-library#1]
```sh
❯ ./scripts/vscode
Creating VS Code Settings at:

  /Users/mando/Github/template-reason-library/.vscode/settings.json

r
```
FYI. Thanks for sharing.

While I am here is `https://github.com/kyldvs/template-reason-library/tree/main/test_exe.esy.lock` necessary? If so, how do you generate it?

**Comment by kyldvs** [comment]
Hey that's odd, it should prompt you to continue and you have to type y/n:

- https://github.com/kyldvs/template-reason-library/blob/main/scripts/vscode#L23

Make sure you are using bash and this file is getting sourced properly, you can add in some echoes around these places to try to figure out what's going on:

- https://github.com/kyldvs/template-reason-library/blob/main/scripts/vscode#L3-L6
- https://github.com/kyldvs/template-reason-library/blob/main/scripts/bash_utils#L75-L88

---

That lock file comes from here I think:

- https://github.com/kyldvs/template-reason-library/blob/main/tests/dune#L16

It should get generated when running the test command, may also need an `esy @test install` or something, but I think the normal `esy test` command that's set up should get everything:

- https://github.com/kyldvs/template-reason-library/blob/main/package.json#L22
